const rows = [
  ["Anime Streaming Apps", "https://fmhy.net/video/#anime-streaming-apps", "Index / Apps"],
  ["Wotaku", "https://wotaku.wiki/websites", "Anime Site Index"],
  ["The Index", "https://theindex.moe/library/anime", "Anime Site Index"],
  ["The Wiki", "https://thewiki.moe/", "Wiki"],
  ["EverythingMoe", "https://everythingmoe.com/", "Anime Site Index"],
  ["EverythingMoe (mirror)", "https://everythingmoe.org/", "Mirror"],
  ["Miruro", "https://www.miruro.com/", "Hard Subs / Soft Subs / Dub / Auto-Next"],
  ["Miruro (mirror)", "https://miruro.tv/", "Mirror"],
  ["Miruro (mirror)", "https://miruro.bz/", "Mirror"],
  ["Miruro (mirror)", "https://miruro.ru/", "Mirror"],
  ["Miruro (mirror)", "https://miruro.to/", "Mirror"],
  ["Miruro Status", "https://status.miruro.com/", "Status"],
  ["animepahe", "https://animepahe.pw/", "Hard Sub / Dub / Some NSFW"],
  ["animepahe Enhancements", "https://update.greasyfork.org/scripts/520048/AnimePahe%20Improvements.user.js", "Userscript"],
  ["animepahe-dl", "https://github.com/KevCui/animepahe-dl", "Downloader"],
  ["KickAssAnime", "https://kaa.lt/", "Sub / Dub / Auto-Next"],
  ["MKissa", "https://mkissa.to/", "Sub / Dub"],
  ["All Manga", "https://allmanga.to/", "Sub / Dub"],
  ["AnimeX", "https://animex.one/", "Sub / Dub / Auto-Next"],
  ["Anikoto", "https://anikototv.to/", "Sub / Dub / Auto-Next"],
  ["Anisuge", "https://animesuge.cz/", "Sub / Dub / Auto-Next"],
  ["Anikoto Backup", "https://anikoto.site/", "Backup"],
  ["Anisuge Backup", "https://animesuge.bid/", "Backup"],
  ["Anidap", "https://anidap.lol/", "Sub / Dub / Auto-Next"],
  ["Re:ANIME", "https://reanime.to/", "Sub / Dub / Auto-Next"],
  ["Re:ANIME mirror", "https://reanime.cz/", "Mirror"],
  ["Re:ANIME mirror", "https://reanime.wtf/", "Mirror"],
  ["Reindex", "https://reindex.to/", "Index"],
  ["Restatus", "https://restatus.me/", "Status"],
  ["Anistream", "https://anistream.one/", "Sub / Dub / Auto-Next"],
  ["Kazora", "https://kazora.cc/", "Sub / Dub / Auto-Next"],
  ["Lunar", "https://lunarx.to/", "Sub / Dub"],
  ["KuroAnime", "https://kuroanime.lol/", "Sub / Dub / Auto-Next"],
  ["NekoWatch", "https://nekowatch.xyz/", "Sub / Dub / Auto-Next"],
  ["JustAnime", "https://justanime.to/", "Sub / Dub / Auto-Next"],
  ["JustAnime Mirrors", "https://projectjust.xyz/", "Mirrors"],
  ["AniLight", "https://anilight.live/", "Sub / Dub / Auto-Next"],
  ["AniKuro", "https://anikuro.to/", "Sub / Dub"],
  ["AniKuro mirror", "https://anikuro.ru/", "Mirror"],
  ["AniKuro Status", "https://anikuro.site/", "Status"],
  ["MeguAnimes", "https://meguanime.com/", "Sub / Dub / Auto-Next"],
  ["Aniwave", "https://aniwaves.ru/", "Sub / Dub / Auto-Next"],
  ["HiAnime mirror", "https://hianimes.ru/", "Sub / Dub / Auto-Next"],
  ["123anime", "https://123animehub.cc/", "Sub / Dub / Auto-Next"],
  ["Senshi", "https://senshi.to/", "Sub / Dub / Auto-Next"],
  ["AniZone", "https://anizone.to/", "Sub"],
  ["AniDoor", "https://anidoor.me/", "Sub / Dub / Auto-Next"],
  ["AniSnatch", "https://anisnatch.top/", "Sub / Dub"],
  ["AniSnatch mirror", "https://anisnatch.site/", "Mirror"],
  ["AnimeStream", "https://anime.uniquestream.net/", "Sub / 720p"],
  ["KoToTV", "https://kototv.to/", "Sub / Dub / Auto-Next"],
  ["Anime Nexus", "https://anime.nexus/", "Sub / Dub"],
  ["LuffyTV", "https://luffytv.live/", "Sub / Dub"],
  ["LuffyTV mirror", "https://luffytv.online/", "Mirror"],
  ["AniChan", "https://anichan.to/", "Sub / Dub"],
  ["AnimeParadise", "https://www.animeparadise.moe/", "Sub / Dub"],
  ["AnimeDex", "https://animedex.fun/", "Sub / Dub"],
  ["Anify", "https://anify.to/", "Sub / Dub"],
  ["AniDB (.app)", "https://anidb.app/", "Sub / Dub"],
  ["Enma", "https://www.enma.lol/", "Sub / Dub / Auto-Next"],
  ["Anikura", "https://anikura.club/", "Sub / Dub"],
  ["1Anime", "https://1ani.me/", "Sub / Dub / Auto-Next"],
  ["Kyren", "https://kyren.moe/", "Sub / Dub"],
  ["Yenime", "https://yenime.net/", "Sub / Dub"],
  ["AnimeNoSub", "https://animenosub.to/", "Sub / Dub"],
  ["AnimeOnsen", "https://animeonsen.xyz/", "Sub / 720p"],
  ["Yomi", "https://yomi.to/", "Sub / Dub / Auto-Next"],
  ["Babyanime", "https://babyanime.top/", "Sub / Dub"],
  ["AniClipse", "https://aniclipse.com/", "Sub / Dub"],
  ["AniHQ", "https://anihq.cc/", "Sub / Dub"],
  ["Luna", "https://luna-stream.me/", "Sub / Dub"],
  ["AniNami", "https://aninami.site/", "Sub / Dub"],
  ["Rive Anime", "https://www.rivestream.app/", "Sub / Dub / Auto-Next"],
  ["Rive Anime mirror", "https://rivestream.ru/", "Mirror"],
  ["Rive Anime Status", "https://rentry.co/rivestream", "Status"],
  ["Kawaii Anime", "https://kawaiianime.cc/", "Sub / Dub"],
  ["FireAnime", "https://fireani.me/", "Sub"],
  ["9anime", "https://9animstv.to/", "Sub / Dub"],
  ["bAnime", "https://banime.dedyn.io/", "Sub / Dub"],
  ["PirateXplay", "https://piratexplay.cc/home", "Sub"],
  ["PirateXplay mirror", "https://piratexplay.com/", "Mirror"],
  ["Kuroiru", "https://kuroiru.co/", "Multi-Site Anime Search"],
  ["Anime Streaming CSE", "https://cse.google.com/cse?cx=006516753008110874046%3Avzcl7wcfhei", "Multi-Site Anime Search"],
  ["AnimeXin", "https://animexin.dev/", "Donghua / Sub"],
  ["Lucifer Donghua", "https://luciferdonghua.in/", "Donghua / Sub"],
  ["LMANIME", "https://lmanime.com/", "Donghua / Sub"],
  ["CKSub", "https://donghua4k.net/", "Donghua / Sub"],
  ["MyAnime", "https://myanime.live/", "Donghua / Sub"],
  ["AnimeKhor", "https://animekhor.org/", "Donghua / Sub"],
  ["Crimson Subs", "https://crimsonfansubs.com/", "Donghua / Sub"],
];

const esc = (v) => String(v).replace(/'/g, "''");
const values = rows.map((r) => `('${esc(r[0])}', '${esc(r[1])}', '${esc(r[2])}')`).join(",\n  ");

const sql = `insert into anime_sites (name, url, description) values\n  ${values};`;
const fs = await import("node:fs");
fs.writeFileSync("sql/02-seed.sql", sql);
console.log(`Wrote ${rows.length} rows to sql/02-seed.sql`);